apiVersion: v1
data:
  password: U29tM1Bhc3N3ZA==
kind: Secret
metadata:
  name: postgres-secret-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      type: database
  template:
    metadata:
      labels:
        app: postgres
        type: database
    spec:
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: init-script
          configMap:
            name: postgres-init-script
      containers:
      - name: postgres
        image: postgres:11@sha256:5d2aa4a7b5f9bdadeddcf87cf7f90a176737a02a30d917de4ab2e6a329bd2d45
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-config
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-storage
          - name: init-script
            mountPath: /docker-entrypoint-initdb.d/init-user-db.sh
            subPath: init-user-db.sh
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres
    type: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432