// Code generated by plugins/sql-server/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:sql-server` or
// `go generate ./plugins/sql-server/...`.
const uiChecksum = "d990cbae0dceeef1b0148b34a3634cd6af8d11d227e5c6b5d4a14ed814d7fd31"
