// Code generated by plugins/sql-server/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:sql-server` or
// `go generate ./plugins/sql-server/...`.
const uiChecksum = "62c4623b35fc3637fc4a821f5bc863e8b386e5f5830cdd68e3a88c98e6dc1a3b"
