version: "2"
linters:
  settings:
    govet:
      disable:
        - printf
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - staticcheck
        text: 'QF1008:'
      - linters:
          - staticcheck
        text: 'SA1019:.*WithCredentialsJSON'
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
