//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"
	"github.com/flanksource/duty/types"
	runtime "k8s.io/apimachinery/pkg/runtime"
	timex "time"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConnection) DeepCopyInto(out *AWSConnection) {
	*out = *in
	in.AccessKey.DeepCopyInto(&out.AccessKey)
	in.SecretKey.DeepCopyInto(&out.SecretKey)
	in.SessionToken.DeepCopyInto(&out.SessionToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConnection.
func (in *AWSConnection) DeepCopy() *AWSConnection {
	if in == nil {
		return nil
	}
	out := new(AWSConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConnection) DeepCopyInto(out *AzureConnection) {
	*out = *in
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConnection.
func (in *AzureConnection) DeepCopy() *AzureConnection {
	if in == nil {
		return nil
	}
	out := new(AzureConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDevopsPipeline) DeepCopyInto(out *AzureDevopsPipeline) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDevopsPipeline.
func (in *AzureDevopsPipeline) DeepCopy() *AzureDevopsPipeline {
	if in == nil {
		return nil
	}
	out := new(AzureDevopsPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDevopsPipelineAction) DeepCopyInto(out *AzureDevopsPipelineAction) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
	out.Pipeline = in.Pipeline
	in.Parameters.DeepCopyInto(&out.Parameters)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDevopsPipelineAction.
func (in *AzureDevopsPipelineAction) DeepCopy() *AzureDevopsPipelineAction {
	if in == nil {
		return nil
	}
	out := new(AzureDevopsPipelineAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureDevopsPipelineParameters) DeepCopyInto(out *AzureDevopsPipelineParameters) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.TemplateParameters != nil {
		in, out := &in.TemplateParameters, &out.TemplateParameters
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.StagesToSkip != nil {
		in, out := &in.StagesToSkip, &out.StagesToSkip
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureDevopsPipelineParameters.
func (in *AzureDevopsPipelineParameters) DeepCopy() *AzureDevopsPipelineParameters {
	if in == nil {
		return nil
	}
	out := new(AzureDevopsPipelineParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Connection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAWS) DeepCopyInto(out *ConnectionAWS) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.AccessKey.DeepCopyInto(&out.AccessKey)
	in.SecretKey.DeepCopyInto(&out.SecretKey)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAWS.
func (in *ConnectionAWS) DeepCopy() *ConnectionAWS {
	if in == nil {
		return nil
	}
	out := new(ConnectionAWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAWSS3) DeepCopyInto(out *ConnectionAWSS3) {
	*out = *in
	in.ConnectionAWS.DeepCopyInto(&out.ConnectionAWS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAWSS3.
func (in *ConnectionAWSS3) DeepCopy() *ConnectionAWSS3 {
	if in == nil {
		return nil
	}
	out := new(ConnectionAWSS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAzure) DeepCopyInto(out *ConnectionAzure) {
	*out = *in
	in.ClientID.DeepCopyInto(&out.ClientID)
	in.ClientSecret.DeepCopyInto(&out.ClientSecret)
	in.TenantID.DeepCopyInto(&out.TenantID)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAzure.
func (in *ConnectionAzure) DeepCopy() *ConnectionAzure {
	if in == nil {
		return nil
	}
	out := new(ConnectionAzure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAzureDevops) DeepCopyInto(out *ConnectionAzureDevops) {
	*out = *in
	in.PersonalAccessToken.DeepCopyInto(&out.PersonalAccessToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAzureDevops.
func (in *ConnectionAzureDevops) DeepCopy() *ConnectionAzureDevops {
	if in == nil {
		return nil
	}
	out := new(ConnectionAzureDevops)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionDiscord) DeepCopyInto(out *ConnectionDiscord) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionDiscord.
func (in *ConnectionDiscord) DeepCopy() *ConnectionDiscord {
	if in == nil {
		return nil
	}
	out := new(ConnectionDiscord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionFolder) DeepCopyInto(out *ConnectionFolder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionFolder.
func (in *ConnectionFolder) DeepCopy() *ConnectionFolder {
	if in == nil {
		return nil
	}
	out := new(ConnectionFolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionGCP) DeepCopyInto(out *ConnectionGCP) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	in.Certificate.DeepCopyInto(&out.Certificate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionGCP.
func (in *ConnectionGCP) DeepCopy() *ConnectionGCP {
	if in == nil {
		return nil
	}
	out := new(ConnectionGCP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionGit) DeepCopyInto(out *ConnectionGit) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionGit.
func (in *ConnectionGit) DeepCopy() *ConnectionGit {
	if in == nil {
		return nil
	}
	out := new(ConnectionGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionGitHub) DeepCopyInto(out *ConnectionGitHub) {
	*out = *in
	in.PersonalAccessToken.DeepCopyInto(&out.PersonalAccessToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionGitHub.
func (in *ConnectionGitHub) DeepCopy() *ConnectionGitHub {
	if in == nil {
		return nil
	}
	out := new(ConnectionGitHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionGitLab) DeepCopyInto(out *ConnectionGitLab) {
	*out = *in
	in.PersonalAccessToken.DeepCopyInto(&out.PersonalAccessToken)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionGitLab.
func (in *ConnectionGitLab) DeepCopy() *ConnectionGitLab {
	if in == nil {
		return nil
	}
	out := new(ConnectionGitLab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionHTTP) DeepCopyInto(out *ConnectionHTTP) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionHTTP.
func (in *ConnectionHTTP) DeepCopy() *ConnectionHTTP {
	if in == nil {
		return nil
	}
	out := new(ConnectionHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionKubernetes) DeepCopyInto(out *ConnectionKubernetes) {
	*out = *in
	in.Certificate.DeepCopyInto(&out.Certificate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionKubernetes.
func (in *ConnectionKubernetes) DeepCopy() *ConnectionKubernetes {
	if in == nil {
		return nil
	}
	out := new(ConnectionKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionList) DeepCopyInto(out *ConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionList.
func (in *ConnectionList) DeepCopy() *ConnectionList {
	if in == nil {
		return nil
	}
	out := new(ConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionMSSQL) DeepCopyInto(out *ConnectionMSSQL) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Host.DeepCopyInto(&out.Host)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Database.DeepCopyInto(&out.Database)
	if in.TrustServerCertificate != nil {
		in, out := &in.TrustServerCertificate, &out.TrustServerCertificate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionMSSQL.
func (in *ConnectionMSSQL) DeepCopy() *ConnectionMSSQL {
	if in == nil {
		return nil
	}
	out := new(ConnectionMSSQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionMongo) DeepCopyInto(out *ConnectionMongo) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Host.DeepCopyInto(&out.Host)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Database.DeepCopyInto(&out.Database)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionMongo.
func (in *ConnectionMongo) DeepCopy() *ConnectionMongo {
	if in == nil {
		return nil
	}
	out := new(ConnectionMongo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionMySQL) DeepCopyInto(out *ConnectionMySQL) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Host.DeepCopyInto(&out.Host)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Database.DeepCopyInto(&out.Database)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionMySQL.
func (in *ConnectionMySQL) DeepCopy() *ConnectionMySQL {
	if in == nil {
		return nil
	}
	out := new(ConnectionMySQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionNtfy) DeepCopyInto(out *ConnectionNtfy) {
	*out = *in
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionNtfy.
func (in *ConnectionNtfy) DeepCopy() *ConnectionNtfy {
	if in == nil {
		return nil
	}
	out := new(ConnectionNtfy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPostgres) DeepCopyInto(out *ConnectionPostgres) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Host.DeepCopyInto(&out.Host)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Database.DeepCopyInto(&out.Database)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPostgres.
func (in *ConnectionPostgres) DeepCopy() *ConnectionPostgres {
	if in == nil {
		return nil
	}
	out := new(ConnectionPostgres)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPrometheus) DeepCopyInto(out *ConnectionPrometheus) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	in.Authentication.DeepCopyInto(&out.Authentication)
	in.Bearer.DeepCopyInto(&out.Bearer)
	in.OAuth.DeepCopyInto(&out.OAuth)
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPrometheus.
func (in *ConnectionPrometheus) DeepCopy() *ConnectionPrometheus {
	if in == nil {
		return nil
	}
	out := new(ConnectionPrometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPushbullet) DeepCopyInto(out *ConnectionPushbullet) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPushbullet.
func (in *ConnectionPushbullet) DeepCopy() *ConnectionPushbullet {
	if in == nil {
		return nil
	}
	out := new(ConnectionPushbullet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPushover) DeepCopyInto(out *ConnectionPushover) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPushover.
func (in *ConnectionPushover) DeepCopy() *ConnectionPushover {
	if in == nil {
		return nil
	}
	out := new(ConnectionPushover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSFTP) DeepCopyInto(out *ConnectionSFTP) {
	*out = *in
	in.Host.DeepCopyInto(&out.Host)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSFTP.
func (in *ConnectionSFTP) DeepCopy() *ConnectionSFTP {
	if in == nil {
		return nil
	}
	out := new(ConnectionSFTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSMB) DeepCopyInto(out *ConnectionSMB) {
	*out = *in
	in.Server.DeepCopyInto(&out.Server)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Port.DeepCopyInto(&out.Port)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSMB.
func (in *ConnectionSMB) DeepCopy() *ConnectionSMB {
	if in == nil {
		return nil
	}
	out := new(ConnectionSMB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSMTP) DeepCopyInto(out *ConnectionSMTP) {
	*out = *in
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	if in.ToAddresses != nil {
		in, out := &in.ToAddresses, &out.ToAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSMTP.
func (in *ConnectionSMTP) DeepCopy() *ConnectionSMTP {
	if in == nil {
		return nil
	}
	out := new(ConnectionSMTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSlack) DeepCopyInto(out *ConnectionSlack) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSlack.
func (in *ConnectionSlack) DeepCopy() *ConnectionSlack {
	if in == nil {
		return nil
	}
	out := new(ConnectionSlack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(types.JSONStringMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(ConnectionAWS)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ConnectionAWSS3)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(ConnectionAzure)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureDevops != nil {
		in, out := &in.AzureDevops, &out.AzureDevops
		*out = new(ConnectionAzureDevops)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(ConnectionGCP)
		(*in).DeepCopyInto(*out)
	}
	if in.Folder != nil {
		in, out := &in.Folder, &out.Folder
		*out = new(ConnectionFolder)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(ConnectionGit)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(ConnectionGitHub)
		(*in).DeepCopyInto(*out)
	}
	if in.GitLab != nil {
		in, out := &in.GitLab, &out.GitLab
		*out = new(ConnectionGitLab)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(ConnectionHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(ConnectionKubernetes)
		(*in).DeepCopyInto(*out)
	}
	if in.MSSQL != nil {
		in, out := &in.MSSQL, &out.MSSQL
		*out = new(ConnectionMSSQL)
		(*in).DeepCopyInto(*out)
	}
	if in.Mongo != nil {
		in, out := &in.Mongo, &out.Mongo
		*out = new(ConnectionMongo)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(ConnectionMySQL)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(ConnectionPostgres)
		(*in).DeepCopyInto(*out)
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(ConnectionPrometheus)
		(*in).DeepCopyInto(*out)
	}
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(ConnectionSFTP)
		(*in).DeepCopyInto(*out)
	}
	if in.SMB != nil {
		in, out := &in.SMB, &out.SMB
		*out = new(ConnectionSMB)
		(*in).DeepCopyInto(*out)
	}
	if in.Discord != nil {
		in, out := &in.Discord, &out.Discord
		*out = new(ConnectionDiscord)
		**out = **in
	}
	if in.Ntfy != nil {
		in, out := &in.Ntfy, &out.Ntfy
		*out = new(ConnectionNtfy)
		(*in).DeepCopyInto(*out)
	}
	if in.Pushbullet != nil {
		in, out := &in.Pushbullet, &out.Pushbullet
		*out = new(ConnectionPushbullet)
		(*in).DeepCopyInto(*out)
	}
	if in.Pushover != nil {
		in, out := &in.Pushover, &out.Pushover
		*out = new(ConnectionPushover)
		(*in).DeepCopyInto(*out)
	}
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(ConnectionSMTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(ConnectionSlack)
		(*in).DeepCopyInto(*out)
	}
	if in.Telegram != nil {
		in, out := &in.Telegram, &out.Telegram
		*out = new(ConnectionTelegram)
		(*in).DeepCopyInto(*out)
	}
	in.URL.DeepCopyInto(&out.URL)
	in.Port.DeepCopyInto(&out.Port)
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
	in.Certificate.DeepCopyInto(&out.Certificate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionTelegram) DeepCopyInto(out *ConnectionTelegram) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
	in.Chats.DeepCopyInto(&out.Chats)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionTelegram.
func (in *ConnectionTelegram) DeepCopy() *ConnectionTelegram {
	if in == nil {
		return nil
	}
	out := new(ConnectionTelegram)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecAction) DeepCopyInto(out *ExecAction) {
	*out = *in
	in.Connections.DeepCopyInto(&out.Connections)
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]Artifact, len(*in))
		copy(*out, *in)
	}
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]types.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Checkout != nil {
		in, out := &in.Checkout, &out.Checkout
		*out = new(GitCheckout)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecAction.
func (in *ExecAction) DeepCopy() *ExecAction {
	if in == nil {
		return nil
	}
	out := new(ExecAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecConnections) DeepCopyInto(out *ExecConnections) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureConnection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecConnections.
func (in *ExecConnections) DeepCopy() *ExecConnections {
	if in == nil {
		return nil
	}
	out := new(ExecConnections)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPConnection) DeepCopyInto(out *GCPConnection) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPConnection.
func (in *GCPConnection) DeepCopy() *GCPConnection {
	if in == nil {
		return nil
	}
	out := new(GCPConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitCheckout) DeepCopyInto(out *GitCheckout) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(types.EnvVar)
		(*in).DeepCopyInto(*out)
	}
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitCheckout.
func (in *GitCheckout) DeepCopy() *GitCheckout {
	if in == nil {
		return nil
	}
	out := new(GitCheckout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsAction) DeepCopyInto(out *GitOpsAction) {
	*out = *in
	in.Repo.DeepCopyInto(&out.Repo)
	out.Commit = in.Commit
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(GitOpsActionPR)
		(*in).DeepCopyInto(*out)
	}
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]GitOpsActionPatch, len(*in))
		copy(*out, *in)
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]GitOpsActionFile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsAction.
func (in *GitOpsAction) DeepCopy() *GitOpsAction {
	if in == nil {
		return nil
	}
	out := new(GitOpsAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsActionCommit) DeepCopyInto(out *GitOpsActionCommit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsActionCommit.
func (in *GitOpsActionCommit) DeepCopy() *GitOpsActionCommit {
	if in == nil {
		return nil
	}
	out := new(GitOpsActionCommit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsActionFile) DeepCopyInto(out *GitOpsActionFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsActionFile.
func (in *GitOpsActionFile) DeepCopy() *GitOpsActionFile {
	if in == nil {
		return nil
	}
	out := new(GitOpsActionFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsActionPR) DeepCopyInto(out *GitOpsActionPR) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsActionPR.
func (in *GitOpsActionPR) DeepCopy() *GitOpsActionPR {
	if in == nil {
		return nil
	}
	out := new(GitOpsActionPR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsActionPatch) DeepCopyInto(out *GitOpsActionPatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsActionPatch.
func (in *GitOpsActionPatch) DeepCopy() *GitOpsActionPatch {
	if in == nil {
		return nil
	}
	out := new(GitOpsActionPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsActionRepo) DeepCopyInto(out *GitOpsActionRepo) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsActionRepo.
func (in *GitOpsActionRepo) DeepCopy() *GitOpsActionRepo {
	if in == nil {
		return nil
	}
	out := new(GitOpsActionRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAction) DeepCopyInto(out *GithubAction) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
	if in.Workflows != nil {
		in, out := &in.Workflows, &out.Workflows
		*out = make([]GithubWorkflow, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAction.
func (in *GithubAction) DeepCopy() *GithubAction {
	if in == nil {
		return nil
	}
	out := new(GithubAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubWorkflow) DeepCopyInto(out *GithubWorkflow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubWorkflow.
func (in *GithubWorkflow) DeepCopy() *GithubWorkflow {
	if in == nil {
		return nil
	}
	out := new(GithubWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAction) DeepCopyInto(out *HTTPAction) {
	*out = *in
	in.HTTPConnection.DeepCopyInto(&out.HTTPConnection)
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]types.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAction.
func (in *HTTPAction) DeepCopy() *HTTPAction {
	if in == nil {
		return nil
	}
	out := new(HTTPAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConnection) DeepCopyInto(out *HTTPConnection) {
	*out = *in
	in.Authentication.DeepCopyInto(&out.Authentication)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConnection.
func (in *HTTPConnection) DeepCopy() *HTTPConnection {
	if in == nil {
		return nil
	}
	out := new(HTTPConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentRule) DeepCopyInto(out *IncidentRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentRule.
func (in *IncidentRule) DeepCopy() *IncidentRule {
	if in == nil {
		return nil
	}
	out := new(IncidentRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentRuleList) DeepCopyInto(out *IncidentRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncidentRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentRuleList.
func (in *IncidentRuleList) DeepCopy() *IncidentRuleList {
	if in == nil {
		return nil
	}
	out := new(IncidentRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentRuleStatus) DeepCopyInto(out *IncidentRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentRuleStatus.
func (in *IncidentRuleStatus) DeepCopy() *IncidentRuleStatus {
	if in == nil {
		return nil
	}
	out := new(IncidentRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notification) DeepCopyInto(out *Notification) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notification.
func (in *Notification) DeepCopy() *Notification {
	if in == nil {
		return nil
	}
	out := new(Notification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Notification) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationAction) DeepCopyInto(out *NotificationAction) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationAction.
func (in *NotificationAction) DeepCopy() *NotificationAction {
	if in == nil {
		return nil
	}
	out := new(NotificationAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationList) DeepCopyInto(out *NotificationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Notification, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationList.
func (in *NotificationList) DeepCopy() *NotificationList {
	if in == nil {
		return nil
	}
	out := new(NotificationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotificationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRecipientSpec) DeepCopyInto(out *NotificationRecipientSpec) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRecipientSpec.
func (in *NotificationRecipientSpec) DeepCopy() *NotificationRecipientSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationRecipientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RepeatGroup != nil {
		in, out := &in.RepeatGroup, &out.RepeatGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.To.DeepCopyInto(&out.To)
	if in.WaitFor != nil {
		in, out := &in.WaitFor, &out.WaitFor
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationStatus) DeepCopyInto(out *NotificationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationStatus.
func (in *NotificationStatus) DeepCopy() *NotificationStatus {
	if in == nil {
		return nil
	}
	out := new(NotificationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Permission) DeepCopyInto(out *Permission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Permission.
func (in *Permission) DeepCopy() *Permission {
	if in == nil {
		return nil
	}
	out := new(Permission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Playbook) DeepCopyInto(out *Playbook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Playbook.
func (in *Playbook) DeepCopy() *Playbook {
	if in == nil {
		return nil
	}
	out := new(Playbook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Playbook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookAction) DeepCopyInto(out *PlaybookAction) {
	*out = *in
	if in.delay != nil {
		in, out := &in.delay, &out.delay
		*out = new(timex.Duration)
		**out = **in
	}
	if in.timeout != nil {
		in, out := &in.timeout, &out.timeout
		*out = new(timex.Duration)
		**out = **in
	}
	if in.RunsOn != nil {
		in, out := &in.RunsOn, &out.RunsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecAction)
		(*in).DeepCopyInto(*out)
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Github != nil {
		in, out := &in.Github, &out.Github
		*out = new(GithubAction)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureDevopsPipeline != nil {
		in, out := &in.AzureDevopsPipeline, &out.AzureDevopsPipeline
		*out = new(AzureDevopsPipelineAction)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPAction)
		(*in).DeepCopyInto(*out)
	}
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(SQLAction)
		**out = **in
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(PodAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Notification != nil {
		in, out := &in.Notification, &out.Notification
		*out = new(NotificationAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookAction.
func (in *PlaybookAction) DeepCopy() *PlaybookAction {
	if in == nil {
		return nil
	}
	out := new(PlaybookAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookApproval) DeepCopyInto(out *PlaybookApproval) {
	*out = *in
	in.Approvers.DeepCopyInto(&out.Approvers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookApproval.
func (in *PlaybookApproval) DeepCopy() *PlaybookApproval {
	if in == nil {
		return nil
	}
	out := new(PlaybookApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookApprovers) DeepCopyInto(out *PlaybookApprovers) {
	*out = *in
	if in.People != nil {
		in, out := &in.People, &out.People
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookApprovers.
func (in *PlaybookApprovers) DeepCopy() *PlaybookApprovers {
	if in == nil {
		return nil
	}
	out := new(PlaybookApprovers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookEventWebhookAuth) DeepCopyInto(out *PlaybookEventWebhookAuth) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(PlaybookEventWebhookAuthBasic)
		(*in).DeepCopyInto(*out)
	}
	if in.Github != nil {
		in, out := &in.Github, &out.Github
		*out = new(PlaybookEventWebhookAuthGithub)
		(*in).DeepCopyInto(*out)
	}
	if in.SVIX != nil {
		in, out := &in.SVIX, &out.SVIX
		*out = new(PlaybookEventWebhookAuthSVIX)
		(*in).DeepCopyInto(*out)
	}
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(PlaybookEventWebhookAuthJWT)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookEventWebhookAuth.
func (in *PlaybookEventWebhookAuth) DeepCopy() *PlaybookEventWebhookAuth {
	if in == nil {
		return nil
	}
	out := new(PlaybookEventWebhookAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookEventWebhookAuthBasic) DeepCopyInto(out *PlaybookEventWebhookAuthBasic) {
	*out = *in
	in.Username.DeepCopyInto(&out.Username)
	in.Password.DeepCopyInto(&out.Password)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookEventWebhookAuthBasic.
func (in *PlaybookEventWebhookAuthBasic) DeepCopy() *PlaybookEventWebhookAuthBasic {
	if in == nil {
		return nil
	}
	out := new(PlaybookEventWebhookAuthBasic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookEventWebhookAuthGithub) DeepCopyInto(out *PlaybookEventWebhookAuthGithub) {
	*out = *in
	in.Token.DeepCopyInto(&out.Token)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookEventWebhookAuthGithub.
func (in *PlaybookEventWebhookAuthGithub) DeepCopy() *PlaybookEventWebhookAuthGithub {
	if in == nil {
		return nil
	}
	out := new(PlaybookEventWebhookAuthGithub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookEventWebhookAuthJWT) DeepCopyInto(out *PlaybookEventWebhookAuthJWT) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookEventWebhookAuthJWT.
func (in *PlaybookEventWebhookAuthJWT) DeepCopy() *PlaybookEventWebhookAuthJWT {
	if in == nil {
		return nil
	}
	out := new(PlaybookEventWebhookAuthJWT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookEventWebhookAuthSVIX) DeepCopyInto(out *PlaybookEventWebhookAuthSVIX) {
	*out = *in
	in.Secret.DeepCopyInto(&out.Secret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookEventWebhookAuthSVIX.
func (in *PlaybookEventWebhookAuthSVIX) DeepCopy() *PlaybookEventWebhookAuthSVIX {
	if in == nil {
		return nil
	}
	out := new(PlaybookEventWebhookAuthSVIX)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookList) DeepCopyInto(out *PlaybookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Playbook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookList.
func (in *PlaybookList) DeepCopy() *PlaybookList {
	if in == nil {
		return nil
	}
	out := new(PlaybookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlaybookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookParameter) DeepCopyInto(out *PlaybookParameter) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookParameter.
func (in *PlaybookParameter) DeepCopy() *PlaybookParameter {
	if in == nil {
		return nil
	}
	out := new(PlaybookParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookSpec) DeepCopyInto(out *PlaybookSpec) {
	*out = *in
	if in.On != nil {
		in, out := &in.On, &out.On
		*out = new(PlaybookTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.RunsOn != nil {
		in, out := &in.RunsOn, &out.RunsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]types.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]Permission, len(*in))
		copy(*out, *in)
	}
	if in.Configs != nil {
		in, out := &in.Configs, &out.Configs
		*out = make(types.ResourceSelectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make(types.ResourceSelectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(types.ResourceSelectors, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]PlaybookParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]PlaybookAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(PlaybookApproval)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookSpec.
func (in *PlaybookSpec) DeepCopy() *PlaybookSpec {
	if in == nil {
		return nil
	}
	out := new(PlaybookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookStatus) DeepCopyInto(out *PlaybookStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookStatus.
func (in *PlaybookStatus) DeepCopy() *PlaybookStatus {
	if in == nil {
		return nil
	}
	out := new(PlaybookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookTrigger) DeepCopyInto(out *PlaybookTrigger) {
	*out = *in
	in.PlaybookTriggerEvents.DeepCopyInto(&out.PlaybookTriggerEvents)
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(PlaybookTriggerWebhook)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookTrigger.
func (in *PlaybookTrigger) DeepCopy() *PlaybookTrigger {
	if in == nil {
		return nil
	}
	out := new(PlaybookTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookTriggerEvent) DeepCopyInto(out *PlaybookTriggerEvent) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookTriggerEvent.
func (in *PlaybookTriggerEvent) DeepCopy() *PlaybookTriggerEvent {
	if in == nil {
		return nil
	}
	out := new(PlaybookTriggerEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookTriggerEvents) DeepCopyInto(out *PlaybookTriggerEvents) {
	*out = *in
	if in.Canary != nil {
		in, out := &in.Canary, &out.Canary
		*out = make([]PlaybookTriggerEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make([]PlaybookTriggerEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Component != nil {
		in, out := &in.Component, &out.Component
		*out = make([]PlaybookTriggerEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookTriggerEvents.
func (in *PlaybookTriggerEvents) DeepCopy() *PlaybookTriggerEvents {
	if in == nil {
		return nil
	}
	out := new(PlaybookTriggerEvents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybookTriggerWebhook) DeepCopyInto(out *PlaybookTriggerWebhook) {
	*out = *in
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(PlaybookEventWebhookAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybookTriggerWebhook.
func (in *PlaybookTriggerWebhook) DeepCopy() *PlaybookTriggerWebhook {
	if in == nil {
		return nil
	}
	out := new(PlaybookTriggerWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAction) DeepCopyInto(out *PodAction) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
	if in.Artifacts != nil {
		in, out := &in.Artifacts, &out.Artifacts
		*out = make([]Artifact, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAction.
func (in *PodAction) DeepCopy() *PodAction {
	if in == nil {
		return nil
	}
	out := new(PodAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLAction) DeepCopyInto(out *SQLAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLAction.
func (in *SQLAction) DeepCopy() *SQLAction {
	if in == nil {
		return nil
	}
	out := new(SQLAction)
	in.DeepCopyInto(out)
	return out
}
