// gen-checksum hashes every file in ui/frontend/dist (the vite build output)
// and writes the result into ui/bundle_checksum.go. Invoked by
// `go generate ./ui/...` (see ui/assets.go's //go:generate directive) and by
// the Taskfile's go:build dependency chain.
//
// The checksum becomes the ETag on the SPA shell so any change to any asset
// invalidates the browser cache for index.html, even though the hashed
// filenames inside assets/ already invalidate themselves.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	outputPath = "bundle_checksum.go"
	distRoot   = "frontend/dist"
)

func main() {
	files, err := collectFiles(distRoot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-checksum: walk %s: %v\n", distRoot, err)
		os.Exit(1)
	}
	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "gen-checksum: no files under %s\n", distRoot)
		os.Exit(1)
	}

	hasher := sha256.New()
	for _, path := range files {
		// Mix the relative path in so renames change the checksum even if the
		// file body is identical.
		rel, _ := filepath.Rel(distRoot, path)
		fmt.Fprintln(hasher, filepath.ToSlash(rel))

		f, err := os.Open(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-checksum: open %s: %v\n", path, err)
			os.Exit(1)
		}
		if _, err := io.Copy(hasher, f); err != nil {
			f.Close()
			fmt.Fprintf(os.Stderr, "gen-checksum: read %s: %v\n", path, err)
			os.Exit(1)
		}
		f.Close()
	}

	sum := hex.EncodeToString(hasher.Sum(nil))

	contents := fmt.Sprintf(`// Code generated by ui/internal/gen-checksum. DO NOT EDIT.

package ui

// BundleChecksum is the sha256 of every file under ui/frontend/dist.
// Regenerated on every `+"`task go:build`"+` or `+"`go generate ./ui/...`"+`.
const BundleChecksum = %q
`, sum)

	if err := os.WriteFile(outputPath, []byte(contents), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-checksum: write %s: %v\n", outputPath, err)
		os.Exit(1)
	}
}

func collectFiles(root string) ([]string, error) {
	var files []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		// Skip source maps so dev/release builds with differing sourcemap
		// content don't churn the checksum unnecessarily — the JS/CSS hash
		// is what actually matters for cache busting.
		if strings.HasSuffix(path, ".map") {
			return nil
		}
		files = append(files, path)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	return files, nil
}
