// gen-checksum hashes the UI bundle (ui.js + bundle CSS) and writes the
// result into ui/bundle_checksum.go. Invoked by `go generate ./ui/...`
// (see ui/assets.go's //go:generate directive) and by the Taskfile's
// go:build dependency chain.
//
// The checksum is embedded as a constant so the Go server can use it as
// an ETag on /ui responses: any rebuild of the frontend produces a new
// hash, which invalidates browser caches without changing the HTTP path.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
)

const outputPath = "bundle_checksum.go"

var inputs = []string{
	"frontend/dist/ui.js",
	"frontend/dist/incident-commander-ui.css",
}

func main() {
	hasher := sha256.New()
	for _, path := range inputs {
		f, err := os.Open(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-checksum: open %s: %v\n", path, err)
			os.Exit(1)
		}
		if _, err := io.Copy(hasher, f); err != nil {
			f.Close()
			fmt.Fprintf(os.Stderr, "gen-checksum: read %s: %v\n", path, err)
			os.Exit(1)
		}
		f.Close()
	}

	sum := hex.EncodeToString(hasher.Sum(nil))

	contents := fmt.Sprintf(`// Code generated by ui/internal/gen-checksum. DO NOT EDIT.

package ui

// BundleChecksum is the sha256 of the embedded UI bundle (ui.js + css).
// Regenerated on every `+"`task go:build`"+` or `+"`go generate ./ui/...`"+`.
const BundleChecksum = %q
`, sum)

	if err := os.WriteFile(outputPath, []byte(contents), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-checksum: write %s: %v\n", outputPath, err)
		os.Exit(1)
	}
}
