// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginManifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Operations      []*OperationDef        `protobuf:"bytes,6,rep,name=operations,proto3" json:"operations,omitempty"`
	UiPort          uint32                 `protobuf:"varint,7,opt,name=ui_port,json=uiPort,proto3" json:"ui_port,omitempty"`
	Tabs            []*TabSpec             `protobuf:"bytes,8,rep,name=tabs,proto3" json:"tabs,omitempty"`
	Roles           []*PluginRole          `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *PluginManifest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginManifest) GetOperations() []*OperationDef {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *PluginManifest) GetUiPort() uint32 {
	if x != nil {
		return x.UiPort
	}
	return 0
}

func (x *PluginManifest) GetTabs() []*TabSpec {
	if x != nil {
		return x.Tabs
	}
	return nil
}

func (x *PluginManifest) GetRoles() []*PluginRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type PluginRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRole) Reset() {
	*x = PluginRole{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRole) ProtoMessage() {}

func (x *PluginRole) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRole.ProtoReflect.Descriptor instead.
func (*PluginRole) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TabSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabSpec) Reset() {
	*x = TabSpec{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabSpec) ProtoMessage() {}

func (x *TabSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabSpec.ProtoReflect.Descriptor instead.
func (*TabSpec) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *TabSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TabSpec) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TabSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TabSpec) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type OperationDef struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParamsSchema        *structpb.Struct       `protobuf:"bytes,3,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"`
	ResultMime          string                 `protobuf:"bytes,4,opt,name=result_mime,json=resultMime,proto3" json:"result_mime,omitempty"`
	Scope               string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Destructive         bool                   `protobuf:"varint,6,opt,name=destructive,proto3" json:"destructive,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,7,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	Http                []*HTTPBinding         `protobuf:"bytes,8,rep,name=http,proto3" json:"http,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OperationDef) Reset() {
	*x = OperationDef{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDef) ProtoMessage() {}

func (x *OperationDef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDef.ProtoReflect.Descriptor instead.
func (*OperationDef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *OperationDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperationDef) GetParamsSchema() *structpb.Struct {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

func (x *OperationDef) GetResultMime() string {
	if x != nil {
		return x.ResultMime
	}
	return ""
}

func (x *OperationDef) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OperationDef) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

func (x *OperationDef) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

func (x *OperationDef) GetHttp() []*HTTPBinding {
	if x != nil {
		return x.Http
	}
	return nil
}

type HTTPBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPBinding) Reset() {
	*x = HTTPBinding{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPBinding) ProtoMessage() {}

func (x *HTTPBinding) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPBinding.ProtoReflect.Descriptor instead.
func (*HTTPBinding) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPBinding) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type RegisterRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HostProtocolVersion uint32                 `protobuf:"varint,1,opt,name=host_protocol_version,json=hostProtocolVersion,proto3" json:"host_protocol_version,omitempty"`
	HostVersion         string                 `protobuf:"bytes,2,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	HostBrokerId        uint32                 `protobuf:"varint,3,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`
	Env                 map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetHostProtocolVersion() uint32 {
	if x != nil {
		return x.HostProtocolVersion
	}
	return 0
}

func (x *RegisterRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *RegisterRequest) GetHostBrokerId() uint32 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

func (x *RegisterRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *structpb.Struct       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Warnings      []string               `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	ConfigItemId  string                 `protobuf:"bytes,3,opt,name=config_item_id,json=configItemId,proto3" json:"config_item_id,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *InvokeRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *InvokeRequest) GetConfigItemId() string {
	if x != nil {
		return x.ConfigItemId
	}
	return ""
}

func (x *InvokeRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeResponse) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *InvokeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InvokeResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *InvokeResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

type InvokePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	ParamsJson    []byte                 `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	ConfigItemId  string                 `protobuf:"bytes,4,opt,name=config_item_id,json=configItemId,proto3" json:"config_item_id,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokePluginRequest) Reset() {
	*x = InvokePluginRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokePluginRequest) ProtoMessage() {}

func (x *InvokePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokePluginRequest.ProtoReflect.Descriptor instead.
func (*InvokePluginRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *InvokePluginRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *InvokePluginRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *InvokePluginRequest) GetParamsJson() []byte {
	if x != nil {
		return x.ParamsJson
	}
	return nil
}

func (x *InvokePluginRequest) GetConfigItemId() string {
	if x != nil {
		return x.ConfigItemId
	}
	return ""
}

func (x *InvokePluginRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type OperationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*OperationDef        `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationList) Reset() {
	*x = OperationList{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationList) ProtoMessage() {}

func (x *OperationList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationList.ProtoReflect.Descriptor instead.
func (*OperationList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *OperationList) GetOperations() []*OperationDef {
	if x != nil {
		return x.Operations
	}
	return nil
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HealthStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AgentId       string                 `protobuf:"bytes,5,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]string      `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Health        string                 `protobuf:"bytes,10,opt,name=health,proto3" json:"health,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItem) Reset() {
	*x = ConfigItem{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItem) ProtoMessage() {}

func (x *ConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItem.ProtoReflect.Descriptor instead.
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfigItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigItem) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ConfigItem) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConfigItem) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ConfigItem) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ConfigItem) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConfigItem) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ConfigItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfigItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ConfigItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigItemList) Reset() {
	*x = ConfigItemList{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemList) ProtoMessage() {}

func (x *ConfigItemList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemList.ProtoReflect.Descriptor instead.
func (*ConfigItemList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigItemList) GetItems() []*ConfigItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConfigItemList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetConfigItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigItemRequest) Reset() {
	*x = GetConfigItemRequest{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigItemRequest) ProtoMessage() {}

func (x *GetConfigItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigItemRequest.ProtoReflect.Descriptor instead.
func (*GetConfigItemRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *GetConfigItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourceSelector struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agent          string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Scope          string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Cache          string                 `protobuf:"bytes,3,opt,name=cache,proto3" json:"cache,omitempty"`
	Search         string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,6,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	Id             string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Namespace      string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TagSelector    string                 `protobuf:"bytes,10,opt,name=tag_selector,json=tagSelector,proto3" json:"tag_selector,omitempty"`
	LabelSelector  string                 `protobuf:"bytes,11,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	FieldSelector  string                 `protobuf:"bytes,12,opt,name=field_selector,json=fieldSelector,proto3" json:"field_selector,omitempty"`
	Health         string                 `protobuf:"bytes,13,opt,name=health,proto3" json:"health,omitempty"`
	Types          []string               `protobuf:"bytes,14,rep,name=types,proto3" json:"types,omitempty"`
	Statuses       []string               `protobuf:"bytes,15,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResourceSelector) Reset() {
	*x = ResourceSelector{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSelector) ProtoMessage() {}

func (x *ResourceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSelector.ProtoReflect.Descriptor instead.
func (*ResourceSelector) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceSelector) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ResourceSelector) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ResourceSelector) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ResourceSelector) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ResourceSelector) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResourceSelector) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

func (x *ResourceSelector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceSelector) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceSelector) GetTagSelector() string {
	if x != nil {
		return x.TagSelector
	}
	return ""
}

func (x *ResourceSelector) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

func (x *ResourceSelector) GetFieldSelector() string {
	if x != nil {
		return x.FieldSelector
	}
	return ""
}

func (x *ResourceSelector) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ResourceSelector) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ResourceSelector) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ListConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *ResourceSelector      `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigsRequest) Reset() {
	*x = ListConfigsRequest{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigsRequest) ProtoMessage() {}

func (x *ListConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigsRequest.ProtoReflect.Descriptor instead.
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ListConfigsRequest) GetSelector() *ResourceSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *ListConfigsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConfigsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// GetConnectionRequest asks the host to resolve a connection by one of four
// supported lookups: type, scraper config item, plugin-defined label, or direct
// connection id.
//
// Type and label lookups use spec.connections mappings from the Plugin CRD.
// config_item_id preserves the existing behavior: it resolves the connection
// used by the scraper that created the config item. connection_id resolves a
// Mission Control connection by id; plugins attached to MissionControl::Connection
// config items can pass their config_item_id because connection config item ids
// are the same as the underlying connection ids.
type GetConnectionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*GetConnectionRequest_Type
	//	*GetConnectionRequest_ConfigItemId
	//	*GetConnectionRequest_Label
	//	*GetConnectionRequest_ConnectionId
	Lookup        isGetConnectionRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *GetConnectionRequest) GetLookup() isGetConnectionRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *GetConnectionRequest) GetType() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetConnectionRequest_Type); ok {
			return x.Type
		}
	}
	return ""
}

func (x *GetConnectionRequest) GetConfigItemId() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetConnectionRequest_ConfigItemId); ok {
			return x.ConfigItemId
		}
	}
	return ""
}

func (x *GetConnectionRequest) GetLabel() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetConnectionRequest_Label); ok {
			return x.Label
		}
	}
	return ""
}

func (x *GetConnectionRequest) GetConnectionId() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetConnectionRequest_ConnectionId); ok {
			return x.ConnectionId
		}
	}
	return ""
}

type isGetConnectionRequest_Lookup interface {
	isGetConnectionRequest_Lookup()
}

type GetConnectionRequest_Type struct {
	Type string `protobuf:"bytes,1,opt,name=type,proto3,oneof"` // e.g. "sql", "aws", "kubernetes", "gcp", "azure", "s3"
}

type GetConnectionRequest_ConfigItemId struct {
	ConfigItemId string `protobuf:"bytes,2,opt,name=config_item_id,json=configItemId,proto3,oneof"` // resolve the connection used by this config item's scraper
}

type GetConnectionRequest_Label struct {
	Label string `protobuf:"bytes,3,opt,name=label,proto3,oneof"` // resolve a plugin-defined connection label mapping
}

type GetConnectionRequest_ConnectionId struct {
	ConnectionId string `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3,oneof"` // resolve a Mission Control connection by id
}

func (*GetConnectionRequest_Type) isGetConnectionRequest_Lookup() {}

func (*GetConnectionRequest_ConfigItemId) isGetConnectionRequest_Lookup() {}

func (*GetConnectionRequest_Label) isGetConnectionRequest_Lookup() {}

func (*GetConnectionRequest_ConnectionId) isGetConnectionRequest_Lookup() {}

type ResolvedConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Certificate   string                 `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedConnection) Reset() {
	*x = ResolvedConnection{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedConnection) ProtoMessage() {}

func (x *ResolvedConnection) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedConnection.ProtoReflect.Descriptor instead.
func (*ResolvedConnection) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ResolvedConnection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResolvedConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ResolvedConnection) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResolvedConnection) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResolvedConnection) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ResolvedConnection) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResolvedConnection) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ResolvedConnection) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // debug|info|warn|error
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Artifact) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *ArtifactRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x18missioncontrol.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\x83\x03\n" +
	"\x0ePluginManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12F\n" +
	"\n" +
	"operations\x18\x06 \x03(\v2&.missioncontrol.plugin.v1.OperationDefR\n" +
	"operations\x12\x17\n" +
	"\aui_port\x18\a \x01(\rR\x06uiPort\x125\n" +
	"\x04tabs\x18\b \x03(\v2!.missioncontrol.plugin.v1.TabSpecR\x04tabs\x12:\n" +
	"\x05roles\x18\t \x03(\v2$.missioncontrol.plugin.v1.PluginRoleR\x05roles\"B\n" +
	"\n" +
	"PluginRole\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"[\n" +
	"\aTabSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"\xc9\x02\n" +
	"\fOperationDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\rparams_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\fparamsSchema\x12\x1f\n" +
	"\vresult_mime\x18\x04 \x01(\tR\n" +
	"resultMime\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12 \n" +
	"\vdestructive\x18\x06 \x01(\bR\vdestructive\x121\n" +
	"\x14required_permissions\x18\a \x03(\tR\x13requiredPermissions\x129\n" +
	"\x04http\x18\b \x03(\v2%.missioncontrol.plugin.v1.HTTPBindingR\x04http\"U\n" +
	"\vHTTPBinding\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06methodJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\x04pathR\vresult_mimeR\tstreaming\"\x8c\x02\n" +
	"\x0fRegisterRequest\x122\n" +
	"\x15host_protocol_version\x18\x01 \x01(\rR\x13hostProtocolVersion\x12!\n" +
	"\fhost_version\x18\x02 \x01(\tR\vhostVersion\x12$\n" +
	"\x0ehost_broker_id\x18\x03 \x01(\rR\fhostBrokerId\x12D\n" +
	"\x03env\x18\x04 \x03(\v22.missioncontrol.plugin.v1.RegisterRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x10ConfigureRequest\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettings\"/\n" +
	"\x11ConfigureResponse\x12\x1a\n" +
	"\bwarnings\x18\x01 \x03(\tR\bwarnings\"\xac\x01\n" +
	"\rInvokeRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\fR\n" +
	"paramsJson\x12$\n" +
	"\x0econfig_item_id\x18\x03 \x01(\tR\fconfigItemId\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xb8\x01\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x126\n" +
	"\x04logs\x18\x05 \x03(\v2\".missioncontrol.plugin.v1.LogEntryR\x04logs\"\xca\x01\n" +
	"\x13InvokePluginRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x1f\n" +
	"\vparams_json\x18\x03 \x01(\fR\n" +
	"paramsJson\x12$\n" +
	"\x0econfig_item_id\x18\x04 \x01(\tR\fconfigItemId\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"W\n" +
	"\rOperationList\x12F\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2&.missioncontrol.plugin.v1.OperationDefR\n" +
	"operations\"8\n" +
	"\fHealthStatus\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\x04\n" +
	"\n" +
	"ConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x19\n" +
	"\bagent_id\x18\x05 \x01(\tR\aagentId\x127\n" +
	"\n" +
	"properties\x18\x06 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12/\n" +
	"\x06config\x18\a \x01(\v2\x17.google.protobuf.StructR\x06config\x12H\n" +
	"\x06labels\x18\b \x03(\v20.missioncontrol.plugin.v1.ConfigItem.LabelsEntryR\x06labels\x12B\n" +
	"\x04tags\x18\t \x03(\v2..missioncontrol.plugin.v1.ConfigItem.TagsEntryR\x04tags\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\tR\x06health\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x0eConfigItemList\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.missioncontrol.plugin.v1.ConfigItemR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"&\n" +
	"\x14GetConfigItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa8\x03\n" +
	"\x10ResourceSelector\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x03 \x01(\tR\x05cache\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12'\n" +
	"\x0finclude_deleted\x18\x06 \x01(\bR\x0eincludeDeleted\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12!\n" +
	"\ftag_selector\x18\n" +
	" \x01(\tR\vtagSelector\x12%\n" +
	"\x0elabel_selector\x18\v \x01(\tR\rlabelSelector\x12%\n" +
	"\x0efield_selector\x18\f \x01(\tR\rfieldSelector\x12\x16\n" +
	"\x06health\x18\r \x01(\tR\x06health\x12\x14\n" +
	"\x05types\x18\x0e \x03(\tR\x05types\x12\x1a\n" +
	"\bstatuses\x18\x0f \x03(\tR\bstatuses\"\x8a\x01\n" +
	"\x12ListConfigsRequest\x12F\n" +
	"\bselector\x18\x01 \x01(\v2*.missioncontrol.plugin.v1.ResourceSelectorR\bselector\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x9d\x01\n" +
	"\x14GetConnectionRequest\x12\x14\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x12&\n" +
	"\x0econfig_item_id\x18\x02 \x01(\tH\x00R\fconfigItemId\x12\x16\n" +
	"\x05label\x18\x03 \x01(\tH\x00R\x05label\x12%\n" +
	"\rconnection_id\x18\x04 \x01(\tH\x00R\fconnectionIdB\b\n" +
	"\x06lookup\"\x9e\x02\n" +
	"\x12ResolvedConnection\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12 \n" +
	"\vcertificate\x18\x05 \x01(\tR\vcertificate\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x127\n" +
	"\n" +
	"properties\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xe9\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06fields\x18\x03 \x03(\v2..missioncontrol.plugin.v1.LogEntry.FieldsEntryR\x06fields\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.missioncontrol.plugin.v1.Artifact.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\vArtifactRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url2\xb6\x04\n" +
	"\rPluginService\x12e\n" +
	"\x0eRegisterPlugin\x12).missioncontrol.plugin.v1.RegisterRequest\x1a(.missioncontrol.plugin.v1.PluginManifest\x12d\n" +
	"\tConfigure\x12*.missioncontrol.plugin.v1.ConfigureRequest\x1a+.missioncontrol.plugin.v1.ConfigureResponse\x12Z\n" +
	"\x0eListOperations\x12\x1f.missioncontrol.plugin.v1.Empty\x1a'.missioncontrol.plugin.v1.OperationList\x12[\n" +
	"\x06Invoke\x12'.missioncontrol.plugin.v1.InvokeRequest\x1a(.missioncontrol.plugin.v1.InvokeResponse\x12Q\n" +
	"\x06Health\x12\x1f.missioncontrol.plugin.v1.Empty\x1a&.missioncontrol.plugin.v1.HealthStatus\x12L\n" +
	"\bShutdown\x12\x1f.missioncontrol.plugin.v1.Empty\x1a\x1f.missioncontrol.plugin.v1.Empty2\xb6\x05\n" +
	"\vHostService\x12e\n" +
	"\rGetConfigItem\x12..missioncontrol.plugin.v1.GetConfigItemRequest\x1a$.missioncontrol.plugin.v1.ConfigItem\x12e\n" +
	"\vListConfigs\x12,.missioncontrol.plugin.v1.ListConfigsRequest\x1a(.missioncontrol.plugin.v1.ConfigItemList\x12m\n" +
	"\rGetConnection\x12..missioncontrol.plugin.v1.GetConnectionRequest\x1a,.missioncontrol.plugin.v1.ResolvedConnection\x12J\n" +
	"\x03Log\x12\".missioncontrol.plugin.v1.LogEntry\x1a\x1f.missioncontrol.plugin.v1.Empty\x12Z\n" +
	"\rWriteArtifact\x12\".missioncontrol.plugin.v1.Artifact\x1a%.missioncontrol.plugin.v1.ArtifactRef\x12Y\n" +
	"\fReadArtifact\x12%.missioncontrol.plugin.v1.ArtifactRef\x1a\".missioncontrol.plugin.v1.Artifact\x12g\n" +
	"\fInvokePlugin\x12-.missioncontrol.plugin.v1.InvokePluginRequest\x1a(.missioncontrol.plugin.v1.InvokeResponseB9Z7github.com/flanksource/incident-commander/plugin;pluginb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: missioncontrol.plugin.v1.Empty
	(*PluginManifest)(nil),        // 1: missioncontrol.plugin.v1.PluginManifest
	(*PluginRole)(nil),            // 2: missioncontrol.plugin.v1.PluginRole
	(*TabSpec)(nil),               // 3: missioncontrol.plugin.v1.TabSpec
	(*OperationDef)(nil),          // 4: missioncontrol.plugin.v1.OperationDef
	(*HTTPBinding)(nil),           // 5: missioncontrol.plugin.v1.HTTPBinding
	(*RegisterRequest)(nil),       // 6: missioncontrol.plugin.v1.RegisterRequest
	(*ConfigureRequest)(nil),      // 7: missioncontrol.plugin.v1.ConfigureRequest
	(*ConfigureResponse)(nil),     // 8: missioncontrol.plugin.v1.ConfigureResponse
	(*InvokeRequest)(nil),         // 9: missioncontrol.plugin.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 10: missioncontrol.plugin.v1.InvokeResponse
	(*InvokePluginRequest)(nil),   // 11: missioncontrol.plugin.v1.InvokePluginRequest
	(*OperationList)(nil),         // 12: missioncontrol.plugin.v1.OperationList
	(*HealthStatus)(nil),          // 13: missioncontrol.plugin.v1.HealthStatus
	(*ConfigItem)(nil),            // 14: missioncontrol.plugin.v1.ConfigItem
	(*ConfigItemList)(nil),        // 15: missioncontrol.plugin.v1.ConfigItemList
	(*GetConfigItemRequest)(nil),  // 16: missioncontrol.plugin.v1.GetConfigItemRequest
	(*ResourceSelector)(nil),      // 17: missioncontrol.plugin.v1.ResourceSelector
	(*ListConfigsRequest)(nil),    // 18: missioncontrol.plugin.v1.ListConfigsRequest
	(*GetConnectionRequest)(nil),  // 19: missioncontrol.plugin.v1.GetConnectionRequest
	(*ResolvedConnection)(nil),    // 20: missioncontrol.plugin.v1.ResolvedConnection
	(*LogEntry)(nil),              // 21: missioncontrol.plugin.v1.LogEntry
	(*Artifact)(nil),              // 22: missioncontrol.plugin.v1.Artifact
	(*ArtifactRef)(nil),           // 23: missioncontrol.plugin.v1.ArtifactRef
	nil,                           // 24: missioncontrol.plugin.v1.RegisterRequest.EnvEntry
	nil,                           // 25: missioncontrol.plugin.v1.ConfigItem.LabelsEntry
	nil,                           // 26: missioncontrol.plugin.v1.ConfigItem.TagsEntry
	nil,                           // 27: missioncontrol.plugin.v1.LogEntry.FieldsEntry
	nil,                           // 28: missioncontrol.plugin.v1.Artifact.MetadataEntry
	(*structpb.Struct)(nil),       // 29: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_plugin_proto_depIdxs = []int32{
	4,  // 0: missioncontrol.plugin.v1.PluginManifest.operations:type_name -> missioncontrol.plugin.v1.OperationDef
	3,  // 1: missioncontrol.plugin.v1.PluginManifest.tabs:type_name -> missioncontrol.plugin.v1.TabSpec
	2,  // 2: missioncontrol.plugin.v1.PluginManifest.roles:type_name -> missioncontrol.plugin.v1.PluginRole
	29, // 3: missioncontrol.plugin.v1.OperationDef.params_schema:type_name -> google.protobuf.Struct
	5,  // 4: missioncontrol.plugin.v1.OperationDef.http:type_name -> missioncontrol.plugin.v1.HTTPBinding
	24, // 5: missioncontrol.plugin.v1.RegisterRequest.env:type_name -> missioncontrol.plugin.v1.RegisterRequest.EnvEntry
	29, // 6: missioncontrol.plugin.v1.ConfigureRequest.settings:type_name -> google.protobuf.Struct
	30, // 7: missioncontrol.plugin.v1.InvokeRequest.deadline:type_name -> google.protobuf.Timestamp
	21, // 8: missioncontrol.plugin.v1.InvokeResponse.logs:type_name -> missioncontrol.plugin.v1.LogEntry
	30, // 9: missioncontrol.plugin.v1.InvokePluginRequest.deadline:type_name -> google.protobuf.Timestamp
	4,  // 10: missioncontrol.plugin.v1.OperationList.operations:type_name -> missioncontrol.plugin.v1.OperationDef
	29, // 11: missioncontrol.plugin.v1.ConfigItem.properties:type_name -> google.protobuf.Struct
	29, // 12: missioncontrol.plugin.v1.ConfigItem.config:type_name -> google.protobuf.Struct
	25, // 13: missioncontrol.plugin.v1.ConfigItem.labels:type_name -> missioncontrol.plugin.v1.ConfigItem.LabelsEntry
	26, // 14: missioncontrol.plugin.v1.ConfigItem.tags:type_name -> missioncontrol.plugin.v1.ConfigItem.TagsEntry
	14, // 15: missioncontrol.plugin.v1.ConfigItemList.items:type_name -> missioncontrol.plugin.v1.ConfigItem
	17, // 16: missioncontrol.plugin.v1.ListConfigsRequest.selector:type_name -> missioncontrol.plugin.v1.ResourceSelector
	29, // 17: missioncontrol.plugin.v1.ResolvedConnection.properties:type_name -> google.protobuf.Struct
	30, // 18: missioncontrol.plugin.v1.ResolvedConnection.expires_at:type_name -> google.protobuf.Timestamp
	27, // 19: missioncontrol.plugin.v1.LogEntry.fields:type_name -> missioncontrol.plugin.v1.LogEntry.FieldsEntry
	30, // 20: missioncontrol.plugin.v1.LogEntry.ts:type_name -> google.protobuf.Timestamp
	28, // 21: missioncontrol.plugin.v1.Artifact.metadata:type_name -> missioncontrol.plugin.v1.Artifact.MetadataEntry
	6,  // 22: missioncontrol.plugin.v1.PluginService.RegisterPlugin:input_type -> missioncontrol.plugin.v1.RegisterRequest
	7,  // 23: missioncontrol.plugin.v1.PluginService.Configure:input_type -> missioncontrol.plugin.v1.ConfigureRequest
	0,  // 24: missioncontrol.plugin.v1.PluginService.ListOperations:input_type -> missioncontrol.plugin.v1.Empty
	9,  // 25: missioncontrol.plugin.v1.PluginService.Invoke:input_type -> missioncontrol.plugin.v1.InvokeRequest
	0,  // 26: missioncontrol.plugin.v1.PluginService.Health:input_type -> missioncontrol.plugin.v1.Empty
	0,  // 27: missioncontrol.plugin.v1.PluginService.Shutdown:input_type -> missioncontrol.plugin.v1.Empty
	16, // 28: missioncontrol.plugin.v1.HostService.GetConfigItem:input_type -> missioncontrol.plugin.v1.GetConfigItemRequest
	18, // 29: missioncontrol.plugin.v1.HostService.ListConfigs:input_type -> missioncontrol.plugin.v1.ListConfigsRequest
	19, // 30: missioncontrol.plugin.v1.HostService.GetConnection:input_type -> missioncontrol.plugin.v1.GetConnectionRequest
	21, // 31: missioncontrol.plugin.v1.HostService.Log:input_type -> missioncontrol.plugin.v1.LogEntry
	22, // 32: missioncontrol.plugin.v1.HostService.WriteArtifact:input_type -> missioncontrol.plugin.v1.Artifact
	23, // 33: missioncontrol.plugin.v1.HostService.ReadArtifact:input_type -> missioncontrol.plugin.v1.ArtifactRef
	11, // 34: missioncontrol.plugin.v1.HostService.InvokePlugin:input_type -> missioncontrol.plugin.v1.InvokePluginRequest
	1,  // 35: missioncontrol.plugin.v1.PluginService.RegisterPlugin:output_type -> missioncontrol.plugin.v1.PluginManifest
	8,  // 36: missioncontrol.plugin.v1.PluginService.Configure:output_type -> missioncontrol.plugin.v1.ConfigureResponse
	12, // 37: missioncontrol.plugin.v1.PluginService.ListOperations:output_type -> missioncontrol.plugin.v1.OperationList
	10, // 38: missioncontrol.plugin.v1.PluginService.Invoke:output_type -> missioncontrol.plugin.v1.InvokeResponse
	13, // 39: missioncontrol.plugin.v1.PluginService.Health:output_type -> missioncontrol.plugin.v1.HealthStatus
	0,  // 40: missioncontrol.plugin.v1.PluginService.Shutdown:output_type -> missioncontrol.plugin.v1.Empty
	14, // 41: missioncontrol.plugin.v1.HostService.GetConfigItem:output_type -> missioncontrol.plugin.v1.ConfigItem
	15, // 42: missioncontrol.plugin.v1.HostService.ListConfigs:output_type -> missioncontrol.plugin.v1.ConfigItemList
	20, // 43: missioncontrol.plugin.v1.HostService.GetConnection:output_type -> missioncontrol.plugin.v1.ResolvedConnection
	0,  // 44: missioncontrol.plugin.v1.HostService.Log:output_type -> missioncontrol.plugin.v1.Empty
	23, // 45: missioncontrol.plugin.v1.HostService.WriteArtifact:output_type -> missioncontrol.plugin.v1.ArtifactRef
	22, // 46: missioncontrol.plugin.v1.HostService.ReadArtifact:output_type -> missioncontrol.plugin.v1.Artifact
	10, // 47: missioncontrol.plugin.v1.HostService.InvokePlugin:output_type -> missioncontrol.plugin.v1.InvokeResponse
	35, // [35:48] is the sub-list for method output_type
	22, // [22:35] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[19].OneofWrappers = []any{
		(*GetConnectionRequest_Type)(nil),
		(*GetConnectionRequest_ConfigItemId)(nil),
		(*GetConnectionRequest_Label)(nil),
		(*GetConnectionRequest_ConnectionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
