// Code generated by plugins/arthas/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:arthas` or
// `go generate ./plugins/arthas/...`.
const uiChecksum = "408745a38070a8b6e5dcdca8307126dbd0455222d9a212da5df55f7ed1c756d2"
