// Code generated by plugins/arthas/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:arthas` or
// `go generate ./plugins/arthas/...`.
const uiChecksum = "a188ce523d3427e76626d1c284cd113ca76cd40fc46ea0d088c7b0079d537ed7"
