// gen-checksum hashes every file under plugins/sql-server/ui/ and writes
// the result to ui_checksum.go. Invoked by `go generate ./plugins/sql-server/...`
// and by the Taskfile's `build:plugin:sql-server` chain.
//
// The checksum is appended to the plugin's manifest version so the iframe URL
// the frontend constructs (`?config_id=…&_v=<sha>`) changes whenever the UI
// bundle changes, forcing browsers to bypass any stale cache.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
)

const (
	outputPath = "ui_checksum.go"
	uiDir      = "ui"
)

func main() {
	files, err := walk(uiDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-checksum: walk %s: %v\n", uiDir, err)
		os.Exit(1)
	}

	hasher := sha256.New()
	for _, path := range files {
		f, err := os.Open(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen-checksum: open %s: %v\n", path, err)
			os.Exit(1)
		}
		fmt.Fprintf(hasher, "%s\x00", path)
		if _, err := io.Copy(hasher, f); err != nil {
			f.Close()
			fmt.Fprintf(os.Stderr, "gen-checksum: read %s: %v\n", path, err)
			os.Exit(1)
		}
		f.Close()
	}

	sum := hex.EncodeToString(hasher.Sum(nil))

	contents := fmt.Sprintf(`// Code generated by plugins/sql-server/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `+"`task build:plugin:sql-server`"+` or
// `+"`go generate ./plugins/sql-server/...`"+`.
const uiChecksum = %q
`, sum)

	if err := os.WriteFile(outputPath, []byte(contents), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-checksum: write %s: %v\n", outputPath, err)
		os.Exit(1)
	}
}

func walk(root string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		out = append(out, path)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(out)
	return out, nil
}
