package notification_test

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"sync"
	"testing"

	"github.com/emersion/go-smtp"
	"github.com/flanksource/commons/logger"
	"github.com/flanksource/duty/context"
	"github.com/flanksource/duty/models"
	"github.com/flanksource/duty/tests/fixtures/dummy"
	"github.com/flanksource/duty/tests/setup"
	"github.com/google/uuid"
	ginkgo "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"

	"github.com/flanksource/incident-commander/api"
	v1 "github.com/flanksource/incident-commander/api/v1"
	"github.com/flanksource/incident-commander/db"
	"github.com/flanksource/incident-commander/events"
	"github.com/flanksource/incident-commander/mail"
)

func TestNotifications(t *testing.T) {
	RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "Notification")
}

var (
	DefaultContext context.Context
)

var _ = ginkgo.BeforeSuite(func() {
	DefaultContext = setup.BeforeSuiteFn()

	// TODO: add a system user to dummy fixtures
	api.SystemUserID = &dummy.JohnDoe.ID

	_ = context.UpdateProperty(DefaultContext, api.PropertyIncidentsDisabled, "true")
	_ = context.UpdateProperty(DefaultContext, "notification.send.trace", "true")
	events.StartConsumers(DefaultContext)
	setupWebhookServer()
	setupSMTPServer()
	setupSystemSMTPConnection()
})

var _ = ginkgo.AfterSuite(func() {
	// setup.DumpEventQueue(DefaultContext)
	if err := cleanupSystemSMTPConnection(); err != nil {
		logger.Errorf("Fail to cleanup system SMTP connection: %v", err)
	}
	if smtpServer != nil {
		if err := smtpServer.Close(); err != nil {
			logger.Errorf("Failed to close SMTP server: %v", err)
		}
	}
	setup.AfterSuiteFn()
	if err := webhookServer.Close(); err != nil {
		logger.Errorf("Fail to close webhook server: %v", err)
	}
})

var (
	webhookServer   *http.Server
	webhookEndpoint string            // the autogenerated endpoint for our webhook
	webhookPostdata map[string]string // JSON message sent by shoutrrr to our webhook
)

var (
	smtpServer           *smtp.Server
	smtpEndpoint         string
	smtpPort             int
	smtpBackend          *captureBackend
	systemSMTPConnection *v1.Connection
)

func setupWebhookServer() {
	listener, err := net.Listen("tcp", ":0") // will assign a random port
	if err != nil {
		ginkgo.Fail(err.Error())
	}

	if addr, ok := listener.Addr().(*net.TCPAddr); ok {
		webhookEndpoint = fmt.Sprintf("http://localhost:%d/webhook", addr.Port)
	} else {
		ginkgo.Fail("unexpected error: failed to parse port.")
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/webhook", func(w http.ResponseWriter, r *http.Request) {
		logger.Infof("Received webhook")
		defer r.Body.Close()

		if err := json.NewDecoder(r.Body).Decode(&webhookPostdata); err != nil {
			logger.Errorf("failed to unmarshall: %v", err)
			w.WriteHeader(http.StatusBadRequest)
			return
		}

		w.WriteHeader(http.StatusOK)
	})

	webhookServer = &http.Server{
		Handler: mux,
	}

	go func() {
		defer ginkgo.GinkgoRecover() // Required by ginkgo, if an assertion is made in a goroutine.

		log.Printf("Starting webhook server on %s", listener.Addr().String())
		if err := webhookServer.Serve(listener); err != nil {
			if err == http.ErrServerClosed {
				logger.Infof("Server closed")
			} else {
				ginkgo.Fail(fmt.Sprintf("Failed to start test server: %v", err))
			}
		}
	}()
}

type capturedMessage struct {
	From string
	To   []string
	Data []byte
}

type captureBackend struct {
	mu       sync.Mutex
	messages []capturedMessage
}

func (b *captureBackend) NewSession(_ *smtp.Conn) (smtp.Session, error) {
	return &captureSession{backend: b}, nil
}

func (b *captureBackend) GetMessages() []capturedMessage {
	b.mu.Lock()
	defer b.mu.Unlock()
	result := make([]capturedMessage, len(b.messages))
	copy(result, b.messages)
	return result
}

func (b *captureBackend) Clear() {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.messages = nil
}

type captureSession struct {
	backend *captureBackend
	from    string
	to      []string
}

func (s *captureSession) Mail(from string, _ *smtp.MailOptions) error {
	s.from = from
	return nil
}

func (s *captureSession) Rcpt(to string, _ *smtp.RcptOptions) error {
	s.to = append(s.to, to)
	return nil
}

func (s *captureSession) Data(r io.Reader) error {
	data, err := io.ReadAll(r)
	if err != nil {
		return err
	}

	s.backend.mu.Lock()
	s.backend.messages = append(s.backend.messages, capturedMessage{
		From: s.from,
		To:   s.to,
		Data: data,
	})
	s.backend.mu.Unlock()
	return nil
}

func (s *captureSession) Reset() {
	s.from = ""
	s.to = nil
}

func (s *captureSession) Logout() error {
	return nil
}

func setupSMTPServer() {
	smtpBackend = &captureBackend{}

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		ginkgo.Fail(err.Error())
	}

	addr, ok := listener.Addr().(*net.TCPAddr)
	if !ok {
		ginkgo.Fail("failed to parse port")
	}
	smtpPort = addr.Port
	smtpEndpoint = fmt.Sprintf("127.0.0.1:%d", smtpPort)

	smtpServer = smtp.NewServer(smtpBackend)
	smtpServer.Domain = "localhost"
	smtpServer.AllowInsecureAuth = true

	go func() {
		defer ginkgo.GinkgoRecover()
		logger.Infof("Starting test SMTP server on %s", smtpEndpoint)
		if err := smtpServer.Serve(listener); err != nil {
			logger.Infof("SMTP server stopped: %v", err)
		}
	}()
}

func setupSystemSMTPConnection() {
	systemSMTPConnection = &v1.Connection{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "mission-control.flanksource.com/v1",
			Kind:       "Connection",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "system",
			Namespace: "mc",
			UID:       types.UID(uuid.NewString()),
		},
		Spec: v1.ConnectionSpec{
			SMTP: &v1.ConnectionSMTP{
				Host:        "127.0.0.1",
				Port:        smtpPort,
				FromAddress: "no-reply@flanksource.com",
				FromName:    "Mission Control",
				Auth:        v1.SMTPAuthNone,
				Encryption:  v1.EncryptionNone,
				ToAddresses: []string{"no-reply@flanksource.com"},
			},
		},
	}

	Expect(db.PersistConnectionFromCRD(DefaultContext, systemSMTPConnection)).To(Succeed())
	mail.FlushSMTPCache()
}

func cleanupSystemSMTPConnection() error {
	if systemSMTPConnection == nil {
		return nil
	}

	mail.FlushSMTPCache()
	return DefaultContext.DB().
		Where("name = ? AND type = ? AND deleted_at IS NULL", "system", models.ConnectionTypeEmail).
		Delete(&models.Connection{}).
		Error
}

func clearSMTPMessages() {
	if smtpBackend != nil {
		smtpBackend.Clear()
	}
}

func getSMTPMessages() []capturedMessage {
	if smtpBackend == nil {
		return nil
	}
	return smtpBackend.GetMessages()
}
