// Code generated by plugins/kubernetes-logs/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:kubernetes-logs` or
// `go generate ./plugins/kubernetes-logs/...`.
const uiChecksum = "dcd0675e9e159c714843b0874d0bccfafd16b085beb6801f77d518892033f62c"
