// Code generated by plugins/kubernetes-logs/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:kubernetes-logs` or
// `go generate ./plugins/kubernetes-logs/...`.
const uiChecksum = "499c4fd6d24eb6a53cf8c0210a46ac886298535ae49459bec3f08d3bb896d032"
