// Code generated by plugins/postgres/internal/gen-checksum. DO NOT EDIT.

package main

// uiChecksum is the sha256 of every file embedded under ui/.
// Regenerated on every `task build:plugin:postgres` or
// `go generate ./plugins/postgres/...`.
const uiChecksum = "647fd9babe03f25648ac8870d0a4a379acab0380c5ff30ad3d7e4c999dd26297"
