// Code generated by ui/internal/gen-checksum. DO NOT EDIT.

package ui

// BundleChecksum is the sha256 of every file under ui/frontend/dist.
// Regenerated on every `task go:build` or `go generate ./ui/...`.
const BundleChecksum = "14026622af0bc37261e92119da33812d2be38d49c2a2ec90e51529104a54d23f"
