// Code generated by ui/internal/gen-checksum. DO NOT EDIT.

package ui

// BundleChecksum is the sha256 of every file under ui/frontend/dist.
// Regenerated on every `task go:build` or `go generate ./ui/...`.
const BundleChecksum = "4b336bc60dfd493ff4dc147d035ac328015de58b619a13f149104af4a2356219"
