// Code generated by ui/internal/gen-checksum. DO NOT EDIT.

package ui

// BundleChecksum is the sha256 of every file under ui/frontend/dist.
// Regenerated on every `task go:build` or `go generate ./ui/...`.
const BundleChecksum = "4da87070fbc2885e029ebe2adbce7f2cc09d2197e7ab7e215a61ad730cde64cf"
