//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package api

import (
	"github.com/flanksource/duty/types"
	timex "time"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoClose) DeepCopyInto(out *AutoClose) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoClose.
func (in *AutoClose) DeepCopy() *AutoClose {
	if in == nil {
		return nil
	}
	out := new(AutoClose)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisplayTable) DeepCopyInto(out *DisplayTable) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisplayTable.
func (in *DisplayTable) DeepCopy() *DisplayTable {
	if in == nil {
		return nil
	}
	out := new(DisplayTable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Filter) DeepCopyInto(out *Filter) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Category != nil {
		in, out := &in.Category, &out.Category
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Age != nil {
		in, out := &in.Age, &out.Age
		*out = new(timex.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Filter.
func (in *Filter) DeepCopy() *Filter {
	if in == nil {
		return nil
	}
	out := new(Filter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubIssue) DeepCopyInto(out *GithubIssue) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubIssue.
func (in *GithubIssue) DeepCopy() *GithubIssue {
	if in == nil {
		return nil
	}
	out := new(GithubIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HoursOfOperation) DeepCopyInto(out *HoursOfOperation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HoursOfOperation.
func (in *HoursOfOperation) DeepCopy() *HoursOfOperation {
	if in == nil {
		return nil
	}
	out := new(HoursOfOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentResponders) DeepCopyInto(out *IncidentResponders) {
	*out = *in
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = make([]Email, len(*in))
		copy(*out, *in)
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = make([]Jira, len(*in))
		copy(*out, *in)
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = make([]CloudProvider, len(*in))
		copy(*out, *in)
	}
	if in.AMS != nil {
		in, out := &in.AMS, &out.AMS
		*out = make([]CloudProvider, len(*in))
		copy(*out, *in)
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = make([]CloudProvider, len(*in))
		copy(*out, *in)
	}
	if in.ServiceNow != nil {
		in, out := &in.ServiceNow, &out.ServiceNow
		*out = make([]ServiceNow, len(*in))
		copy(*out, *in)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = make([]Slack, len(*in))
		copy(*out, *in)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]TeamsChannel, len(*in))
		copy(*out, *in)
	}
	if in.TeamsUser != nil {
		in, out := &in.TeamsUser, &out.TeamsUser
		*out = make([]TeamsUser, len(*in))
		copy(*out, *in)
	}
	if in.GithubIssue != nil {
		in, out := &in.GithubIssue, &out.GithubIssue
		*out = make([]GithubIssue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentResponders.
func (in *IncidentResponders) DeepCopy() *IncidentResponders {
	if in == nil {
		return nil
	}
	out := new(IncidentResponders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentRuleSpec) DeepCopyInto(out *IncidentRuleSpec) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]types.ResourceSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Template = in.Template
	in.Filter.DeepCopyInto(&out.Filter)
	if in.HoursOfOperation != nil {
		in, out := &in.HoursOfOperation, &out.HoursOfOperation
		*out = make([]HoursOfOperation, len(*in))
		copy(*out, *in)
	}
	if in.AutoClose != nil {
		in, out := &in.AutoClose, &out.AutoClose
		*out = new(AutoClose)
		**out = **in
	}
	if in.AutoResolve != nil {
		in, out := &in.AutoResolve, &out.AutoResolve
		*out = new(AutoClose)
		**out = **in
	}
	in.IncidentResponders.DeepCopyInto(&out.IncidentResponders)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentRuleSpec.
func (in *IncidentRuleSpec) DeepCopy() *IncidentRuleSpec {
	if in == nil {
		return nil
	}
	out := new(IncidentRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentTemplate) DeepCopyInto(out *IncidentTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentTemplate.
func (in *IncidentTemplate) DeepCopy() *IncidentTemplate {
	if in == nil {
		return nil
	}
	out := new(IncidentTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMContextRequest) DeepCopyInto(out *LLMContextRequest) {
	*out = *in
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = new(TimeMetadata)
		**out = **in
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(TimeMetadata)
		**out = **in
	}
	if in.Relationships != nil {
		in, out := &in.Relationships, &out.Relationships
		*out = make([]LLMContextRequestRelationship, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Playbooks != nil {
		in, out := &in.Playbooks, &out.Playbooks
		*out = make([]LLMContextRequestPlaybook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMContextRequest.
func (in *LLMContextRequest) DeepCopy() *LLMContextRequest {
	if in == nil {
		return nil
	}
	out := new(LLMContextRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMContextRequestPlaybook) DeepCopyInto(out *LLMContextRequestPlaybook) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMContextRequestPlaybook.
func (in *LLMContextRequestPlaybook) DeepCopy() *LLMContextRequestPlaybook {
	if in == nil {
		return nil
	}
	out := new(LLMContextRequestPlaybook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMContextRequestRelationship) DeepCopyInto(out *LLMContextRequestRelationship) {
	*out = *in
	if in.Depth != nil {
		in, out := &in.Depth, &out.Depth
		*out = new(int)
		**out = **in
	}
	out.Changes = in.Changes
	out.Analysis = in.Analysis
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMContextRequestRelationship.
func (in *LLMContextRequestRelationship) DeepCopy() *LLMContextRequestRelationship {
	if in == nil {
		return nil
	}
	out := new(LLMContextRequestRelationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelBargaugeConfig) DeepCopyInto(out *PanelBargaugeConfig) {
	*out = *in
	in.GaugeConfig.DeepCopyInto(&out.GaugeConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelBargaugeConfig.
func (in *PanelBargaugeConfig) DeepCopy() *PanelBargaugeConfig {
	if in == nil {
		return nil
	}
	out := new(PanelBargaugeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelDef) DeepCopyInto(out *PanelDef) {
	*out = *in
	in.PanelMeta.DeepCopyInto(&out.PanelMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelDef.
func (in *PanelDef) DeepCopy() *PanelDef {
	if in == nil {
		return nil
	}
	out := new(PanelDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelGaugeConfig) DeepCopyInto(out *PanelGaugeConfig) {
	*out = *in
	in.GaugeConfig.DeepCopyInto(&out.GaugeConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelGaugeConfig.
func (in *PanelGaugeConfig) DeepCopy() *PanelGaugeConfig {
	if in == nil {
		return nil
	}
	out := new(PanelGaugeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelMeta) DeepCopyInto(out *PanelMeta) {
	*out = *in
	if in.Gauge != nil {
		in, out := &in.Gauge, &out.Gauge
		*out = new(PanelGaugeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Piechart != nil {
		in, out := &in.Piechart, &out.Piechart
		*out = new(PiechartConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Number != nil {
		in, out := &in.Number, &out.Number
		*out = new(PanelNumberConfig)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(PanelTableConfig)
		**out = **in
	}
	if in.Bargauge != nil {
		in, out := &in.Bargauge, &out.Bargauge
		*out = new(PanelBargaugeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelMeta.
func (in *PanelMeta) DeepCopy() *PanelMeta {
	if in == nil {
		return nil
	}
	out := new(PanelMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelNumberConfig) DeepCopyInto(out *PanelNumberConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelNumberConfig.
func (in *PanelNumberConfig) DeepCopy() *PanelNumberConfig {
	if in == nil {
		return nil
	}
	out := new(PanelNumberConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanelTableConfig) DeepCopyInto(out *PanelTableConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanelTableConfig.
func (in *PanelTableConfig) DeepCopy() *PanelTableConfig {
	if in == nil {
		return nil
	}
	out := new(PanelTableConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiechartConfig) DeepCopyInto(out *PiechartConfig) {
	*out = *in
	if in.Colors != nil {
		in, out := &in.Colors, &out.Colors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiechartConfig.
func (in *PiechartConfig) DeepCopy() *PiechartConfig {
	if in == nil {
		return nil
	}
	out := new(PiechartConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Property) DeepCopyInto(out *Property) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(int64)
		**out = **in
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]types.Link, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Property.
func (in *Property) DeepCopy() *Property {
	if in == nil {
		return nil
	}
	out := new(Property)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewVariable) DeepCopyInto(out *ViewVariable) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ViewVariableValueFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewVariable.
func (in *ViewVariable) DeepCopy() *ViewVariable {
	if in == nil {
		return nil
	}
	out := new(ViewVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewVariableValueFrom) DeepCopyInto(out *ViewVariableValueFrom) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewVariableValueFrom.
func (in *ViewVariableValueFrom) DeepCopy() *ViewVariableValueFrom {
	if in == nil {
		return nil
	}
	out := new(ViewVariableValueFrom)
	in.DeepCopyInto(out)
	return out
}
