name: Lint
on:
  pull_request:
permissions: read-all
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clear up disk space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf $AGENT_TOOLSDIRECTORY
          rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: 1.26.x
          cache: false
      - run: make -B manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For deps
      - run: make auth/oidc/static/tailwind.min.js
      - run: make ui
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.11.4
          args: --verbose --max-same-issues=0 --max-issues-per-linter=0
