name: Create Release
on:
  push:
    branches:
      - main

permissions: {} # start with no permission

jobs:
  create-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: flanksource/action-workflows/.github/workflows/create-release.yml@7080efac89b20714a0f7a621bc59794b1b5f1433
    secrets:
      token: ${{ secrets.FLANKBOT }}

  binary:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: create-release
    if: needs.create-release.outputs.published == 'true'
    steps:
      - name: Clear up disk space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf /usr/local/share/boost
          rm -rf $AGENT_TOOLSDIRECTORY
          rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: v1.26.x
          cache: true
      - name: Build release binaries
        run: |
          make ui
          make --jobs=2 binaries
          make package-release
        env:
          VERSION: v${{ needs.create-release.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOFLAGS: -p=2
      - name: Upload binaries to draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "v${{ needs.create-release.outputs.version }}" ./.release/* --clobber --repo "${{ github.repository }}"

  docker:
    needs: create-release
    if: needs.create-release.outputs.published == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: flanksource/action-workflows/.github/workflows/publish-docker-image.yml@7080efac89b20714a0f7a621bc59794b1b5f1433
    with:
      image_tags: |
        flanksource/incident-commander:latest
        flanksource/incident-commander:v${{ needs.create-release.outputs.version }}
        public.ecr.aws/k4y9r6y5/incident-commander:v${{ needs.create-release.outputs.version }}
      platforms: linux/amd64
      login_to_ecr: true
      cache_from: type=gha
      cache_to: type=gha,mode=max
      cosign: true
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      aws_access_key_id: ${{ secrets.ECR_AWS_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      github_token: ${{ secrets.GITHUB_TOKEN }}

  update-incident-commander-chart:
    if: needs.create-release.outputs.published == 'true'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [create-release, docker]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set version
        # Always use root git tags as semantic release can fail due to rate limit
        run: |
          git fetch --prune --unshallow
          echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags --match 'v[0-9]*' | sed -e 's/^v//')" >> $GITHUB_ENV
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: "${{ github.repository_owner }}/mission-control-chart"
          token: ${{ secrets.FLANKBOT }}
          path: ./incident-commander-chart
      - name: Update image tags in chart
        uses: mikefarah/yq@cb9793555487aafb501e1a9d85c28b812aeadfab # master
        with:
          cmd: yq -i e '.image.tag = "v${{ env.RELEASE_VERSION }}"' incident-commander-chart/chart/values.yaml
      - name: Update image tags in agent chart
        uses: mikefarah/yq@cb9793555487aafb501e1a9d85c28b812aeadfab # master
        with:
          cmd: yq -i e '.image.tag = "v${{ env.RELEASE_VERSION }}"' incident-commander-chart/agent-chart/values.yaml
      - name: Update CRDs
        run: |
          cp config/crds/* incident-commander-chart/chart/crds/
          cp config/crds/* incident-commander-chart/crd-chart/templates/
      - name: Push changes to chart repo
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore: update incident-commander image version to ${{ env.RELEASE_VERSION }}"
          repository: ./incident-commander-chart
          branch: main

  publish-release:
    if: needs.create-release.outputs.published == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [create-release, binary, docker, update-incident-commander-chart]
    steps:
      - name: Publish draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit "v${{ needs.create-release.outputs.version }}" --draft=false --repo "${{ github.repository }}"
